### ISSUE TITLE
AttributeError: 'module' object has no attribute 'toimage'

### ISSUE THREAD

**Issue by thinkh** [phovea/phovea_server#25]
* Release number or git hash: 19df2658cfa8da9970f8b3701ff5f476dbc36942
* Web browser version and OS: Windows 10
* Environment (local or deployed): local

### Steps to reproduce

1. Install taco
2. `docker-compose up -d`
3. `npm run start:taco`
4. Open web browser -> http://localhost:8080/api/dataset/matrix/tacoServerTacoMediumOutput/data?format=png&range=&format_min=0&format_max=10
5. Open other CMD and run `docker-compose logs`

### Observed behavior
* Server errors (relevant messages and tracebacks)

```
api_1  | 02:44:41 ERROR phovea_server.dataset_api: Exception on /matrix/tacoServerTacoMediumInput/data [GET]
api_1  | Traceback (most recent call last):
api_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
api_1  |     response = self.full_dispatch_request()
api_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
api_1  |     rv = self.handle_user_exception(e)
api_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
api_1  |     reraise(exc_type, exc_value, tb)
api_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
api_1  |     rv = self.dispatch_request()
api_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
api_1  |     return self.view_functions[rule.endpoint](**req.view_args)
api_1  |   File "phovea_server/phovea_server/dataset_specific.py", line 176, in data_gen
api_1  |     return formatter(d, r, args=ns.request.args)
api_1  |   File "phovea_server/phovea_server/plugin.py", line 46, in __call__
api_1  |     v = m(*args, **kwargs)
api_1  |   File "phovea_server/phovea_server/dataset_specific.py", line 110, in format_image
api_1  |     img = scipy.misc.toimage(d, cmin=cmin, cmax=cmax, pal=_color_palette(args.get('format_palette', None)))
api_1  | AttributeError: 'module' object has no attribute 'toimage'
api_1  | [2017-01-01 02:44:44,255] ERROR in app: Exception on /matrix/tacoServerTacoMediumOutput/data [GET]
api_1  | Traceback (most recent call last):
api_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
api_1  |     response = self.full_dispatch_request()
api_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
api_1  |     rv = self.handle_user_exception(e)
api_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
api_1  |     reraise(exc_type, exc_value, tb)
api_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
api_1  |     rv = self.dispatch_request()
api_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
api_1  |     return self.view_functions[rule.endpoint](**req.view_args)
api_1  |   File "phovea_server/phovea_server/dataset_specific.py", line 176, in data_gen
api_1  |     return formatter(d, r, args=ns.request.args)
api_1  |   File "phovea_server/phovea_server/plugin.py", line 46, in __call__
api_1  |     v = m(*args, **kwargs)
api_1  |   File "phovea_server/phovea_server/dataset_specific.py", line 110, in format_image
api_1  |     img = scipy.misc.toimage(d, cmin=cmin, cmax=cmax, pal=_color_palette(args.get('format_palette', None)))
api_1  | AttributeError: 'module' object has no attribute 'toimage'
api_1  | 02:44:44 ERROR phovea_server.dataset_api: Exception on /matrix/tacoServerTacoMediumOutput/data [GET]
api_1  | Traceback (most recent call last):
api_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
api_1  |     response = self.full_dispatch_request()
api_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
api_1  |     rv = self.handle_user_exception(e)
api_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
api_1  |     reraise(exc_type, exc_value, tb)
api_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
api_1  |     rv = self.dispatch_request()
api_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
api_1  |     return self.view_functions[rule.endpoint](**req.view_args)
api_1  |   File "phovea_server/phovea_server/dataset_specific.py", line 176, in data_gen
api_1  |     return formatter(d, r, args=ns.request.args)
api_1  |   File "phovea_server/phovea_server/plugin.py", line 46, in __call__
api_1  |     v = m(*args, **kwargs)
api_1  |   File "phovea_server/phovea_server/dataset_specific.py", line 110, in format_image
api_1  |     img = scipy.misc.toimage(d, cmin=cmin, cmax=cmax, pal=_color_palette(args.get('format_palette', None)))
api_1  | AttributeError: 'module' object has no attribute 'toimage'
```

### Expected behavior
* No error

**Comment by JauB1981** [comment]
!pip install PILLOW
!pip install scipy==1.0
