### ISSUE TITLE
Index out of range error when accessing data

### ISSUE THREAD

**Issue by alexsb** [phovea/phovea_server#33]
* Release number or git hash: 79e10615374a45adca9b63460792864dcf4fe07d (latest develop)
* Web browser version and OS: Chrome/Mac
* Environment (local or deployed): Local

### Steps to reproduce

Checkout the debug_data branches of lineage and lineage server: 

https://github.com/Caleydo/lineage/tree/debug_data
https://github.com/Caleydo/lineage_server/tree/debug_data

Open localhost. 

### Observed behavior

This is the client error message: 

```
Accessing RelativeID column by name from big-decent-clipped-38 dataset:
ajax.ts:84 GET http://localhost:8080/api/dataset/table/big-decent-clipped-38/col/RelativeID 500 (INTERNAL SERVER ERROR)
(anonymous) @ ajax.ts:84
step @ tslib.es6.js:91
(anonymous) @ tslib.es6.js:72
(anonymous) @ tslib.es6.js:65
__awaiter @ tslib.es6.js:61
send @ ajax.ts:56
getJSON @ ajax.ts:94
getAPIJSON @ ajax.ts:211
col @ loader.ts:146
Table.colData @ Table.ts:67
(anonymous) @ dataExplorations.ts:98
step @ tslib.es6.js:91
(anonymous) @ tslib.es6.js:72
fulfilled @ tslib.es6.js:62
ajax.ts:15 Uncaught (in promise) Error: INTERNAL SERVER ERROR
    at new AjaxError (ajax.ts:15)
    at checkStatus (ajax.ts:25)
    at ajax.ts:84
    at step (tslib.es6.js:91)
    at Object.next (tslib.es6.js:72)
    at fulfilled (tslib.es6.js:62)
AjaxError @ ajax.ts:15
checkStatus @ ajax.ts:25
(anonymous) @ ajax.ts:84
step @ tslib.es6.js:91
(anonymous) @ tslib.es6.js:72
fulfilled @ tslib.es6.js:62
```

This is the server error: 

```
$ docker-compose up
Starting lineage_api_1
Attaching to lineage_api_1
api_1  | configuration file: /phovea/config.json
api_1  | 19:21:39 INFO phovea_server.server: add application: hello_world at namespace: /api/hello_world
api_1  | 19:21:39 INFO phovea_server.server: add application: caleydo-last-deployment at namespace: /api/last_deployment
api_1  | 19:21:39 INFO phovea_server.server: add application: caleydo-dataset at namespace: /api/dataset
api_1  | 19:21:39 INFO phovea_server.server: add application: caleydo-idtype at namespace: /api/idtype
api_1  | 19:21:39 INFO werkzeug:  * Restarting with stat
api_1  | configuration file: /phovea/config.json
api_1  | 19:21:39 INFO phovea_server.server: add application: hello_world at namespace: /api/hello_world
api_1  | 19:21:39 INFO phovea_server.server: add application: caleydo-last-deployment at namespace: /api/last_deployment
api_1  | 19:21:39 INFO phovea_server.server: add application: caleydo-dataset at namespace: /api/dataset
api_1  | 19:21:39 INFO phovea_server.server: add application: caleydo-idtype at namespace: /api/idtype
api_1  | 19:22:33 ERROR phovea_server.dataset_api: Exception on /table/big-decent-clipped-38/col/RelativeID [GET]
api_1  | Traceback (most recent call last):
api_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
api_1  |     response = self.full_dispatch_request()
api_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
api_1  |     rv = self.handle_user_exception(e)
api_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
api_1  |     reraise(exc_type, exc_value, tb)
api_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
api_1  |     rv = self.dispatch_request()
api_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
api_1  |     return self.view_functions[rule.endpoint](**req.view_args)
api_1  |   File "phovea_server/phovea_server/dataset_specific.py", line 197, in col_table
api_1  |     return jsonify(col.aslist(r), allow_nan=False)
api_1  |   File "phovea_server/phovea_server/dataset_csv.py", line 328, in aslist
api_1  |     return self.asnumpy(range).tolist()
api_1  |   File "phovea_server/phovea_server/dataset_csv.py", line 332, in asnumpy
api_1  |     p = self._table.aspandas(range)[self.name]
api_1  |   File "phovea_server/phovea_server/dataset_csv.py", line 376, in aspandas
api_1  |     n = self.load()['df']
api_1  |   File "phovea_server/phovea_server/dataset_csv.py", line 63, in load
api_1  |     self._loaded = self._process(data)
api_1  |   File "phovea_server/phovea_server/dataset_csv.py", line 351, in _process
api_1  |     objs = {c.name: [x[i + 1] for x in data[1:]] for i, c in enumerate(self.columns)}
api_1  |   File "phovea_server/phovea_server/dataset_csv.py", line 351, in <dictcomp>
api_1  |     objs = {c.name: [x[i + 1] for x in data[1:]] for i, c in enumerate(self.columns)}
api_1  | IndexError: list index out of range
api_1  | [2017-02-28 19:22:33,250] ERROR in app: Exception on /table/big-decent-clipped-38/col/RelativeID [GET]
api_1  | Traceback (most recent call last):
api_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
api_1  |     response = self.full_dispatch_request()
api_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
api_1  |     rv = self.handle_user_exception(e)
api_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
api_1  |     reraise(exc_type, exc_value, tb)
api_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
api_1  |     rv = self.dispatch_request()
api_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
api_1  |     return self.view_functions[rule.endpoint](**req.view_args)
api_1  |   File "phovea_server/phovea_server/dataset_specific.py", line 197, in col_table
api_1  |     return jsonify(col.aslist(r), allow_nan=False)
api_1  |   File "phovea_server/phovea_server/dataset_csv.py", line 328, in aslist
api_1  |     return self.asnumpy(range).tolist()
api_1  |   File "phovea_server/phovea_server/dataset_csv.py", line 332, in asnumpy
api_1  |     p = self._table.aspandas(range)[self.name]
api_1  |   File "phovea_server/phovea_server/dataset_csv.py", line 376, in aspandas
api_1  |     n = self.load()['df']
api_1  |   File "phovea_server/phovea_server/dataset_csv.py", line 63, in load
api_1  |     self._loaded = self._process(data)
api_1  |   File "phovea_server/phovea_server/dataset_csv.py", line 351, in _process
api_1  |     objs = {c.name: [x[i + 1] for x in data[1:]] for i, c in enumerate(self.columns)}
api_1  |   File "phovea_server/phovea_server/dataset_csv.py", line 351, in <dictcomp>
api_1  |     objs = {c.name: [x[i + 1] for x in data[1:]] for i, c in enumerate(self.columns)}
api_1  | IndexError: list index out of range

```

### Expected behavior
* being able to access raw data

**Comment by alexsb** [comment]
OK, this change seems to fix the problem: 

https://github.com/Caleydo/lineage_server/commit/11926f1c732876ef1702bb6eefeffa4adf46bc92

**Comment by sgratzl** [comment]
so, it was a configuration issue and not a server bug

**Comment by alexsb** [comment]
Yes; but a better error message if a configuration is wrong would be helpful. I still can't spot why the original json would be wrong - the only major difference is the: 

```
+    ],
 +    "idcolumn": 0
```

**Comment by alexsb** [comment]
It's not the ID column and it's not the size. I have no idea what was wrong...

**Comment by sgratzl** [comment]
your patch adds to each column, the column index: 
e.g. https://github.com/Caleydo/lineage_server/commit/11926f1c732876ef1702bb6eefeffa4adf46bc92#diff-e9c1f69ea339784ff9ac5cc2a1aef030R24

**Comment by sgratzl** [comment]
see also https://github.com/Caleydo/lineage_server/compare/debug_data...minimal_debug_data_path?expand=1
